name: Build and publish images

permissions:
  packages: write

on:
  push:
    tags:
      - "**-**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Tag preprocessing
        uses: actions/github-script@v6
        id: data
        with:
          script: |
            const tag = context.ref.replace('refs/tags/', '');
            const info = tag.split('-');

            if (info.length != 2)
              core.setFailed("Release/tag must contain only a single - (dash) character");

            core.exportVariable("TAG", tag);
            core.exportVariable("DOCKERFILE", "Dockerfile." + info[0]);
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.TAG }}
          file: ${{ env.DOCKERFILE }}