name: Build and publish latest (devel) version of images

permissions:
  packages: write

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - barearm
          # - zephyr
          - esp
          - hdl
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pre-build image and push
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ${{ matrix.variant }}
          imageName: ghcr.io/${{ github.repository }}
          imageTag: ${{ matrix.variant }}-test
          push: always
          runCmd: ./test.sh
